### ISSUE TITLE
Multistitcher not recognizing images

### ISSUE THREAD

**Issue by unhappypanda** [latsic/imgalign#3]
Hello,

If I try to create a panorama of my room and of my friend's room, it seems that the algorithm doesn't recognise a lot of the photographs giving the error "No match found for images with index: [list]" . 

Is there a specific way required to take the photos?

Thanks,

**Comment by latsic** [comment]
When taking pictures inside a room, it is especially important that the camera position is stable. If you take multiple picures of a room, try not to move around to much or not at all if possible. Even better, use a tripod. As a general rule, the closer the objects are you are making pictures of, the more important it is to have a fixed camera position.

Otherwise I would need more information or see the pictures to say why you have problems stitching them together.
